(function(){
'use strict';
if(!document.getElementById('definition'))return;
const rutas={
ababillarse:{ruta:["español baba","babilla","a- + babilla + -arse","español ababillarse"],texto:"El DLE registra «ababillarse», pero no le pone etimología. Es un verbo parasintético sobre babilla (a- + babilla + -arse). De babilla dice el DLE: «Del dim. de baba¹». Fuente de babilla: Diccionario de la lengua española (RAE y ASALE)."},
ababol:{ruta:["latín papāver","árabe hispánico ḥappapáwr","español ababol"],texto:"Del ár. hisp. ḥappapáwr[a], y este del lat. papāver, con infl. del ár. ḥabb 'semillas'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
abaca:{ruta:["tagalo","español abacá"],texto:"De or. tagalo. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
abacal:{ruta:["tagalo","español abacá","español abacal"],texto:"El DLE registra «abacal» y no indica etimología. Es derivado español de abacá, voz que el DLE da como de origen tagalo. Fuente de abacá: Diccionario de la lengua española (RAE y ASALE)."},
abacalero:{ruta:["español abacá","español abacal","español abacalero"],texto:"El DLE registra «abacalero» y no indica etimología. Se forma en español sobre abacal o abacá, con el sufijo -ero."},
abaceria:{ruta:["español abacero","español abacería"],texto:"De abacero. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
abacial:{ruta:["bajo latín abbacialis","español abacial"],texto:"Del b. lat. abbacialis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
abaco:{ruta:["griego ἄβαξ ábax","latín abăcus","español ábaco"],texto:"Del lat. abăcus, y este del gr. ἄβαξ ábax. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
abacora:{ruta:["árabe clásico bākūrah","árabe hispánico albakúra","albacora","español abacora"],texto:"En el DLE, «abacora» remite a albacora², el pez. De albacora² dice: «Quizá de albacora¹». Y de albacora¹: «Del ár. hisp. albakúra, y este del ár. clás. bākūrah 'fruta temprana'». Fuente: Diccionario de la lengua española (RAE y ASALE)."},
babilla:{ruta:["español baba¹","español babilla"],texto:"Del dim. de baba¹, por la semejanza del humor sinovial con la baba. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
token:{ruta:["inglés antiguo tācen «signo, señal»","inglés token"],texto:"«Token» viene del inglés antiguo tācen, que significaba «signo» o «señal». Es una palabra germánica: el alemán Zeichen («signo»), el neerlandés teken y el gótico taikns comparten origen con ella. Fuente: Claude, aportada por el autor del diccionario."},
etimologia:{ruta:["griego ἐτυμολογία etymología","latín etymologĭa","español etimología"],texto:"Del lat. etymologĭa, y este del gr. ἐτυμολογία etymología. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
infinito:{ruta:["latín infinītus","español infinito"],texto:"Del lat. infinītus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
perro:{ruta:["origen incierto","español perro"],texto:"De or. inc. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ser:{ruta:["latín sedēre / esse","español antiguo seer","español ser"],texto:"De seer. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
monstruo:{ruta:["latín monstrum","español monstruo"],texto:"Del lat. monstrum, con infl. de monstruoso. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
tirabuzon:{ruta:["francés tire-bouchon","español tirabuzón"],texto:"Del fr. tire-bouchon. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ropa:{ruta:["germánico *raupjan","gótico *raupa","español ropa"],texto:"Del gót. *raupa 'botín', y este der. del germ. *raupjan 'pelar, arrancar'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ilimitado:{ruta:["latín illimitātus","español ilimitado"],texto:"Del lat. illimitātus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
universo:{ruta:["latín universus","español universo"],texto:"Del lat. universus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
dios:{ruta:["latín deus","español dios"],texto:"Del lat. deus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
cristo:{ruta:["griego Χριστός Christós","latín Christus","español cristo"],texto:"Del lat. Christus, y este del gr. Χριστός Christós; propiamente 'ungido'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
madre:{ruta:["latín mater, -tris","español madre"],texto:"Del lat. mater, -tris. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
realidad:{ruta:["español real","sufijo -idad","español realidad"],texto:"El DLE registra «realidad», pero no trae línea etimológica. Es un derivado transparente de real con el sufijo -idad."},
conciencia:{ruta:["griego syneídēsis","latín conscientĭa","español conciencia"],texto:"Del lat. conscientĭa, y este calco del gr. συνείδησις syneídēsis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
homotecia:{ruta:["español homotético","derivación regresiva","español homotecia"],texto:"Der. regres. de homotético. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
espiritu:{ruta:["latín spirĭtus","español espíritu"],texto:"Del lat. spirĭtus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
alma:{ruta:["latín anĭma","español alma"],texto:"Del lat. anĭma. El DLE recoge además otra etimología: Del hebr. ‘almá. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
messi:{ruta:["apellido Messi","español Messi"],texto:"El DLE no registra «Messi». Es el apellido del futbolista Lionel Messi, de origen italiano, usado aquí como nombre común de su genio goleador."},
genio:{ruta:["latín genius","español genio"],texto:"Del lat. genius. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
inteligencia:{ruta:["latín intelligentia","español inteligencia"],texto:"Del lat. intelligentia. El DLE recoge además otra etimología: Del ruso intelligentzia. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
triangulo:{ruta:["latín triangŭlus","español triángulo"],texto:"Del lat. triangŭlus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
galaxia:{ruta:["griego γαλαξίας galaxías","latín tardío galaxĭas","español galaxia"],texto:"Del lat. tardío galaxĭas 'la Vía Láctea', y este del gr. γαλαξίας galaxías, der. de γάλα, -ακτος gála, -aktos 'leche'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
humano:{ruta:["latín humānus","español humano"],texto:"Del lat. humānus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
caos:{ruta:["griego χάος cháos","latín chaos","español caos"],texto:"Del lat. chaos, y este del gr. χάος cháos; propiamente 'abertura', 'agujero'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
infierno:{ruta:["latín infernum","español infierno"],texto:"Del lat. infernum. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
yo:{ruta:["latín ego","latín vulgar eo","español yo"],texto:"Del lat. vulg. eo, y este del lat. ego. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
unidefinido:{ruta:["latín unus","prefijo uni-","español definido","español unidefinido"],texto:"El DLE no registra «unidefinido». Es una acuñación de este diccionario: uni- («uno») + definido."},
cabra:{ruta:["latín capra","español cabra"],texto:"Del lat. capra. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
jabonoso:{ruta:["español jabón","sufijo -oso","español jabonoso"],texto:"El DLE registra «jabonoso» y no indica etimología. Se forma sobre jabón con el sufijo -oso."},
mundo:{ruta:["griego kósmos","latín mundus","español mundo"],texto:"Del lat. mundus, y este calco del gr. κόσμος kósmos. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
sol:{ruta:["latín sol, solis","español sol"],texto:"Del lat. sol, solis. El DLE recoge además otras etimologías: Apóc. del adv. solo. Del ingl. sol, y este acort. de solution 'solución'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
meme:{ruta:["griego mímēma","inglés meme","español meme"],texto:"Del ingl. meme, palabra acuñada en 1976 por R. Dawkins, biólogo inglés, sobre el modelo de gene 'gen' y a partir del gr. μίμημα mímēma 'cosa que se imita'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
internet:{ruta:["inglés Internet","español internet"],texto:"Del ingl. Internet. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
egoismo:{ruta:["latín ego e -ismo","español egoísmo"],texto:"Del lat. ego 'yo' e -ismo. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
profeta:{ruta:["griego προφήτης prophḗtēs","latín prophēta","español profeta"],texto:"Del lat. prophēta, y este del gr. προφήτης prophḗtēs. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ronaldo:{ruta:["nombre propio Ronaldo","español Ronaldo"],texto:"El DLE no registra «Ronaldo» como voz común. Aquí nombra al futbolista; Ronaldo es forma portuguesa del nombre."},
embarazada:{ruta:["español embarazar","participio","español embarazada"],texto:"Del part. de embarazar. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
nanar:{ruta:["creación expresiva ña-ñar","español ñañar"],texto:"El DLE no registra «ñañar». En este diccionario es una voz expresiva, de reduplicación, para «terminar una frase con la palabra de inicio»."},
judas:{ruta:["Judas Iscariote","español judas"],texto:"Por alus. a Judas Iscariote, por quien Jesús fue vendido a los judíos. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ciceron:{ruta:["M. T. Cicerón","español ciceron"],texto:"Por alus. a M. T. Cicerón, 106-43 a. C., orador romano. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
amar:{ruta:["latín amāre","español amar"],texto:"Del lat. amāre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
odiar:{ruta:["español odio","español odiar"],texto:"El DLE registra «odiar» y no le asigna etimología. Es el verbo correspondiente a odio."},
habitar:{ruta:["latín habitāre","español habitar"],texto:"Del lat. habitāre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
espacio:{ruta:["latín spatium","español espacio"],texto:"Del lat. spatium. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
blanco:{ruta:["germánico *blank","español blanco"],texto:"Del germ. *blank. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
gordo:{ruta:["latín gurdus","español gordo"],texto:"Del lat. gurdus, voz de or. hisp. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
dimension:{ruta:["latín dimensio, -ōnis","español dimension"],texto:"Del lat. dimensio, -ōnis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
cerebro:{ruta:["latín cerebrum","español cerebro"],texto:"Del lat. cerebrum. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
etiologia:{ruta:["griego αἰτιολογία aitiología","español etiología"],texto:"Del gr. αἰτιολογία aitiología. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
librero:{ruta:["latín librarius","español librero"],texto:"Del lat. librarius. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
bbc:{ruta:["Benzema, Bale y Cristiano","sigla BBC"],texto:"El DLE no registra esta sigla. En el diccionario nombra al trío de delanteros del Real Madrid: Benzema, Bale y Cristiano."},
msn:{ruta:["Messi, Suárez y Neymar","sigla MSN"],texto:"El DLE no registra esta sigla. En el diccionario nombra al trío del Barcelona: Messi, Suárez y Neymar."},
google:{ruta:["inglés googol","inglés Google","español Google"],texto:"El DLE no registra «google». Es el nombre comercial inglés del buscador. Sus fundadores lo tomaron de googol, el nombre inglés de un 1 seguido de cien ceros."},
infinitamente:{ruta:["latín infinītus","español infinito","sufijo -mente","español infinitamente"],texto:"El DLE define «infinitamente» como «de modo infinito» y no añade otra etimología. Se forma con infinito (del lat. infinītus) y -mente. Fuente de infinito: Diccionario de la lengua española (RAE y ASALE)."},
idempotente:{ruta:["latín idem y potente","español idempotente"],texto:"Del lat. idem 'el mismo, lo mismo' y potente. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
partivo:{ruta:["latín partīre","español partir","español partitivo","español partivo"],texto:"El DLE no registra «partivo». La voz próxima «partitivo» figura así: «Der. tardío del lat. partīre 'partir'». Fuente de partitivo: Diccionario de la lengua española (RAE y ASALE)."},
adjetivo:{ruta:["latín adiectīvus","español adjetivo"],texto:"Del lat. adiectīvus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
regicida:{ruta:["latín rex, regis y -cida","español regicida"],texto:"Del lat. rex, regis 'rey' y -cida. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ajedrez:{ruta:["sánscrito chaturaṅga","pelvi čatrang","árabe clásico šiṭranǧ","árabe hispánico aššaṭranǧ","español ajedrez"],texto:"Del ár. hisp. aššaṭranǧ o aššiṭranǧ, este del ár. clás. šiṭranǧ, este del pelvi čatrang, y este del sánscr. chaturaṅga 'de cuatro miembros'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
informacion:{ruta:["latín informatio, -ōnis","español información"],texto:"Del lat. informatio, -ōnis 'concepto', 'explicación de una palabra'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
dato:{ruta:["latín datum","español dato"],texto:"Del lat. datum 'lo que se da'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
bidefinido:{ruta:["latín bis","prefijo bi-","español definido","español bidefinido"],texto:"El DLE no registra «bidefinido». Es una acuñación de este diccionario: bi- («dos») + definido."},
tridefinido:{ruta:["latín tres","prefijo tri-","español definido","español tridefinido"],texto:"El DLE no registra «tridefinido». Es una acuñación de este diccionario: tri- («tres») + definido."},
escritor:{ruta:["latín scriptor, -ōris","español escritor"],texto:"Del lat. scriptor, -ōris. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
escribidor:{ruta:["español escribir","sufijo -dor","español escribidor"],texto:"De escribir y -dor. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
loco:{ruta:["árabe clásico lawqā'","árabe hispánico *láwqa","español loco"],texto:"Quizá del ár. hisp. *láwqa, y este del ár. clás. lawqā', f. de alwaq 'estúpido'. El DLE recoge además otra etimología: Voz mapuche. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
misericordia:{ruta:["latín misericordia","español misericordia"],texto:"Del lat. misericordia. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
dibu:{ruta:["Emiliano Martínez","hipocorístico Dibu"],texto:"El DLE no registra «dibu». Aquí es el hipocorístico del portero argentino Emiliano Martínez."},
deporte:{ruta:["español deportarse","español antiguo deporte «diversión»","inglés sport","español deporte"],texto:"Calco del ingl. sport, a partir del desus. deporte 'diversión', y este der. de deportarse 'divertirse'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
nostalgia:{ruta:["griego νόστος nóstos y -αλγία -algía","latín moderno nostalgia","español nostalgia"],texto:"Del lat. mod. nostalgia, y este del gr. νόστος nóstos 'regreso' y -αλγία -algía '-algia'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
conjetura:{ruta:["latín coniectūra","español conjetura"],texto:"Del lat. coniectūra. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
matematica:{ruta:["griego máthēma","griego mathēmatiká","latín mathematĭca","español matemática"],texto:"Del lat. mathematĭca, y este del gr. [τὰ] μαθηματικά [tà] mathēmatiká, der. de μάθημα máthēma 'conocimiento'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
matematico:{ruta:["griego μαθηματικός mathēmatikós","latín mathematĭcus","español matemático"],texto:"Del lat. mathematĭcus, y este del gr. μαθηματικός mathēmatikós. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
dibujar:{ruta:["francés antiguo deboissier","español dibujar"],texto:"Del fr. ant. deboissier. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
dibujo:{ruta:["español dibujar","español dibujo"],texto:"De dibujar. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
laberinto:{ruta:["griego λαβύρινθος labýrinthos","latín labyrinthus","español laberinto"],texto:"Del lat. labyrinthus, y este del gr. λαβύρινθος labýrinthos. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
flaco:{ruta:["latín flaccus","español flaco"],texto:"Del lat. flaccus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
el:{ruta:["latín ille, illa, illud","español el"],texto:"Del lat. ille, illa, illud 'aquel'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
nato:{ruta:["quechua ñatu","español ñato"],texto:"Del quechua ñatu. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
narigon:{ruta:["español nariz","sufijo -ón","español narigón"],texto:"El DLE registra «narigón» (sinónimo de narigudo) y no indica etimología. Es aumentativo de nariz."},
demonio:{ruta:["griego bizantino δαιμόνιον daimónion","latín tardío daemonĭum","español demonio"],texto:"Del lat. tardío daemonĭum, y este del gr. bizant. δαιμόνιον daimónion. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
caron:{ruta:["español cara","sufijo -ón","español carón"],texto:"El DLE registra «carón» («de cara grande», en varios países de América) y no indica etimología. Es aumentativo de cara."},
cono:{ruta:["griego κῶνος kônos","latín conus","español cono"],texto:"Del lat. conus, y este del gr. κῶνος kônos 'piña', 'cono'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
existir:{ruta:["latín exsistĕre","español existir"],texto:"Del lat. exsistĕre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
tenedor:{ruta:["latín tenēre","español tener","sufijo -dor","español tenedor"],texto:"El DLE registra «tenedor» y no indica etimología. Es un derivado de tener con el sufijo -dor: el útil que tiene o sujeta la comida."},
cuchara:{ruta:["español cuchar","español cuchara"],texto:"De cuchar. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
cuchillo:{ruta:["latín culter","latín cultellus","español cuchillo"],texto:"Del lat. cultellus 'cuchillo pequeño', y este dim. de culter 'cuchillo'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
indeterminado:{ruta:["latín indeterminātus","español indeterminado"],texto:"Del lat. indeterminātus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
indefinido:{ruta:["latín indefinītus","español indefinido"],texto:"Del lat. indefinītus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
palindromo:{ruta:["griego παλίνδρομος palíndromos","español palíndromo"],texto:"Del gr. παλίνδρομος palíndromos 'que recorre a la inversa'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
capicua:{ruta:["catalán cap i cua «cabeza y cola»","catalán capicua","español capicúa"],texto:"Del cat. capicua, y este de cap i cua 'cabeza y cola'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
morfema:{ruta:["griego μορφή morphḗ y -ma","español morfema"],texto:"Del gr. μορφή morphḗ 'forma' y -ma. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
virus:{ruta:["latín virus","español virus"],texto:"Del lat. virus 'veneno', 'ponzoña'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
androide:{ruta:["griego anḗr «varón»","latín -oīdes","latín moderno androides","español androide"],texto:"Del lat. mod. androides, y este del gr. ἀνήρ, ἀνδρός anḗr, andrós 'varón' y el lat. -oīdes '-oide'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
robot:{ruta:["checo robota","checo robot","inglés robot","español robot"],texto:"Del ingl. robot, y este del checo robot, de robota 'trabajo, prestación personal'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
maquina:{ruta:["griego dórico μαχανά machaná","latín machĭna","español maquina"],texto:"Del lat. machĭna, y este del gr. dórico μαχανά machaná. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ultrainstinto:{ruta:["japonés migatte no gokui","español ultra-","español instinto","español ultrainstinto"],texto:"El DLE no registra «ultrainstinto». Es el nombre, en el doblaje al español, de la técnica de Dragon Ball (en japonés, migatte no gokui): ultra- + instinto."},
jiren:{ruta:["nombre de ficción Jiren","español Jiren"],texto:"El DLE no registra «Jiren». Es el nombre de un personaje de Dragon Ball Super, no una voz del léxico general."},
nada:{ruta:["latín res nata «cosa nacida»","español nada"],texto:"Del lat. [res] nata '[cosa] nacida'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
gato:{ruta:["latín tardío cattus","español gato"],texto:"Del lat. tardío cattus. El DLE recoge además otras etimologías: Del quechua qhatu 'mercado'. Del fr. gâteau 'pastel'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
precomputada:{ruta:["latín computāre","español computar","prefijo pre-","español precomputada"],texto:"El DLE no registra «precomputada». Es un tecnicismo: pre- + participio de computar («calcular de antemano»)."},
holomorfa:{ruta:["griego hólos «entero»","griego morphḗ «forma»","función holomorfa"],texto:"El DLE no registra «holomorfa». Es un término de las matemáticas, tomado por vía culta del griego hólos («entero, todo») y morphḗ («forma»): función holomorfa, derivable en cada punto."},
meromorfa:{ruta:["griego méros «parte»","griego morphḗ «forma»","función meromorfa"],texto:"El DLE no registra «meromorfa». Es un término matemático, del griego méros («parte») y morphḗ («forma»): función meromorfa, holomorfa salvo en polos."},
jirafa:{ruta:["árabe clásico zurāfah","italiano giraffa","español jirafa"],texto:"Del it. giraffa, y este del ár. clás. zurāfah o zarāfah. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
elefante:{ruta:["griego ἐλέφας eléphas","latín elĕphas, -antis","español elefante"],texto:"Del lat. elĕphas, -antis, y este del gr. ἐλέφας eléphas. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
maradoniano:{ruta:["apellido Maradona","sufijo -iano","español maradoniano"],texto:"El DLE no registra «maradoniano». Se forma con el apellido Maradona y el sufijo -iano; aquí designa un tipo de gol."},
negar:{ruta:["latín negāre","español negar"],texto:"Del lat. negāre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
negacion:{ruta:["latín negatio, -ōnis","español negación"],texto:"Del lat. negatio, -ōnis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
no:{ruta:["latín non","español no"],texto:"Del lat. non. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
hype:{ruta:["inglés hype","español hype"],texto:"El DLE no registra «hype». Es un préstamo del inglés hype, la expectación exagerada ante algo que todavía no llega."},
poder:{ruta:["latín posse","latín vulgar *potēre","español poder"],texto:"Del lat. vulg. *potēre, creado sobre ciertas formas del verbo lat. posse 'poder'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
todar:{ruta:["español todo","sufijo -ar","español todar"],texto:"El DLE no registra «todar». Es una acuñación de este diccionario: el verbo de «el todo», formado con todo + -ar."},
persona:{ruta:["griego prósōpon","etrusco φersu","latín persōna","español persona"],texto:"Del lat. persōna 'máscara de actor', 'personaje teatral', 'persona', este del etrusco φersu, y este del gr. πρόσωπον prósōpon. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
limitado:{ruta:["español limitar","participio","español limitado"],texto:"Del part. de limitar. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
nadie:{ruta:["español antiguo nadi","español nadie"],texto:"De nadi. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
eternamente:{ruta:["latín aeternus","español eterno","sufijo -mente","español eternamente"],texto:"El DLE registra «eternamente» y no trae etimología propia. Es eterno (del lat. aeternus) con -mente. Fuente de eterno: Diccionario de la lengua española (RAE y ASALE)."},
eterno:{ruta:["latín aeternus","español eterno"],texto:"Del lat. aeternus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
todopoderoso:{ruta:["español todo","español poderoso","español todopoderoso"],texto:"El DLE registra «todopoderoso» y no indica etimología. Es un compuesto transparente de todo y poderoso."},
omnipotente:{ruta:["latín omnipŏtens, -entis","español omnipotente"],texto:"Del lat. omnipŏtens, -entis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
aprender:{ruta:["latín apprehendĕre","español aprender"],texto:"Del lat. apprehendĕre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
napolitano:{ruta:["latín Neapolitānus","español napolitano"],texto:"Del lat. Neapolitānus. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ultrabasico:{ruta:["español básico","prefijo ultra-","español ultrabásico"],texto:"El DLE no registra «ultrabásico». En geología se forma con ultra- y básico para las rocas ígneas con muy poca sílice."},
ventes:{ruta:["español -mente","español ventes"],texto:"El DLE no registra «ventes». Es un término de este diccionario para la combinación de un adverbio en -mente con un adjetivo o un participio."},
artificial:{ruta:["latín artificiālis","español artificial"],texto:"Del lat. artificiālis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
muerte:{ruta:["latín mors, mortis","español muerte"],texto:"Del lat. mors, mortis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
hollejo:{ruta:["latín follicŭlus","español hollejo"],texto:"Del lat. follicŭlus 'saco pequeño', 'cascabillo'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
mapear:{ruta:["español mapa","sufijo -ear","español mapear"],texto:"De mapa y -ear. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
patiestevado:{ruta:["español pata","español estevado","español patiestevado"],texto:"El DLE registra «patiestevado» («de piernas arqueadas») y no indica etimología. Es compuesto de pata y estevado."},
sensacion:{ruta:["latín medieval sensatio, -onis","español sensación"],texto:"Del lat. mediev. sensatio, -onis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
epica:{ruta:["griego ἐπικός epikós","latín epĭcus","español epica"],texto:"Del lat. epĭcus, y este del gr. ἐπικός epikós. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
epico:{ruta:["griego ἐπικός epikós","latín epĭcus","español epico"],texto:"Del lat. epĭcus, y este del gr. ἐπικός epikós. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
eliminatoria:{ruta:["español eliminar","sufijo -toria","español eliminatoria"],texto:"El DLE registra «eliminatoria» y no indica etimología. Se forma sobre eliminar con el sufijo -toria."},
intencion:{ruta:["latín intentio, -ōnis","español intencion"],texto:"Del lat. intentio, -ōnis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
epoder:{ruta:["latín vulgar *potēre","español poder","español epoder"],texto:"El DLE no registra «epoder». En este diccionario parte de poder (el DLE: «Del lat. vulg. *potēre») para nombrar el imperio o el dominio. Fuente de poder: Diccionario de la lengua española (RAE y ASALE)."},
puede:{ruta:["latín posse","latín vulgar *potēre","español poder","español puede"],texto:"«Puede» no es un lema aparte: es la tercera persona del presente de indicativo de poder. El DLE etimologiza poder así: «Del lat. vulg. *potēre, creado sobre ciertas formas del verbo lat. posse». Fuente: Diccionario de la lengua española (RAE y ASALE)."},
pueda:{ruta:["latín posse","latín vulgar *potēre","español poder","español pueda"],texto:"«Pueda» no es un lema aparte: es la tercera persona del presente de subjuntivo de poder. El DLE etimologiza poder así: «Del lat. vulg. *potēre, creado sobre ciertas formas del verbo lat. posse». Fuente: Diccionario de la lengua española (RAE y ASALE)."},
clitico:{ruta:["enclítico y proclítico","español clitico"],texto:"Formado sobre enclítico y proclítico. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
enclitico:{ruta:["griego ἐγκλιτικός enklitikós","latín tardío enclitĭcus","español enclitico"],texto:"Del lat. tardío enclitĭcus, y este del gr. ἐγκλιτικός enklitikós; propiamente 'apoyado'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
proclitico:{ruta:["griego enklitikós","latín moderno procliticus","español proclítico"],texto:"Del lat. mod. procliticus, y este formado a partir del gr. ἐγκλιτικός enklitikós 'enclítico'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
googleable:{ruta:["inglés Google","sufijo -able","español googleable"],texto:"El DLE no registra «googleable». Se forma sobre el nombre Google con el sufijo -able: que se puede encontrar en ese buscador."},
ingoogleable:{ruta:["español googleable","prefijo in-","español ingoogleable"],texto:"El DLE no registra «ingoogleable». Es in- + googleable: que no se puede encontrar en Google."},
gugol:{ruta:["inglés infantil googol","inglés googol","español gúgol"],texto:"El DLE no registra «gúgol» ni «gugol». Adapta el inglés googol, palabra acuñada hacia 1920 por Milton Sirotta, sobrino del matemático Edward Kasner, para un 1 seguido de cien ceros. De ahí salió el nombre Google."},
googlear:{ruta:["inglés Google","sufijo -ear","español googlear"],texto:"El DLE no registra «googlear». Es un verbo formado en español sobre Google con -ear («buscar en Google»). La Fundéu ha preferido a menudo «buscar en Google»."},
infinitotriz:{ruta:["latín infinītus","español infinito","sufijo -triz","español infinitotriz"],texto:"El DLE no registra «infinitotriz». Es una acuñación de este diccionario: infinito (del lat. infinītus) + el sufijo -triz. Fuente de infinito: Diccionario de la lengua española (RAE y ASALE)."},
soltero:{ruta:["latín solitarius","español soltero"],texto:"Del lat. solitarius 'solitario, aislado'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
escobeta:{ruta:["español escoba","sufijo -eta","español escobeta"],texto:"De escoba y -eta. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
simular:{ruta:["latín simulāre","español simular"],texto:"Del lat. simulāre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
atar:{ruta:["latín aptāre","español atar"],texto:"Del lat. aptāre 'ajustar, adaptar'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
subir:{ruta:["latín subīre","español subir"],texto:"Del lat. subīre 'acercarse a un lugar alto desde abajo'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
llorar:{ruta:["latín plorāre","español llorar"],texto:"Del lat. plorāre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ciclo:{ruta:["griego κύκλος kýklos","latín cyclus","español ciclo"],texto:"Del lat. cyclus, y este del gr. κύκλος kýklos 'círculo', 'rueda'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
agujero:{ruta:["español aguja","sufijo -ero","español agujero"],texto:"De aguja y -ero. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
negro:{ruta:["latín niger, nigri","español negro"],texto:"Del lat. niger, nigri. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
vestir:{ruta:["latín vestīre","español vestir"],texto:"Del lat. vestīre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
vencer:{ruta:["latín vincĕre","español vencer"],texto:"Del lat. vincĕre. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
criba:{ruta:["español cribo","español criba"],texto:"De cribo. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
limite:{ruta:["latín limes, -ĭtis","español limite"],texto:"Del lat. limes, -ĭtis. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
tarado:{ruta:["español tarar","participio","español tarado"],texto:"Del part. de tarar. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
ventura:{ruta:["latín ventūra, pl. de ventūrum","español ventura"],texto:"Del lat. ventūra, pl. de ventūrum 'lo por venir'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
eco:{ruta:["griego ἠχώ ēchṓ","latín echo","español eco"],texto:"Del lat. echo, y este del gr. ἠχώ ēchṓ. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
inefable:{ruta:["latín ineffabĭlis","español inefable"],texto:"Del lat. ineffabĭlis 'indecible'. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
infinitesimal:{ruta:["francés infinitésimal","español infinitesimal"],texto:"Del fr. infinitésimal. Fuente: Diccionario de la lengua española (RAE y ASALE)."},
infinidad:{ruta:["latín infinĭtas, -ātis","español infinidad"],texto:"Del lat. infinĭtas, -ātis. Fuente: Diccionario de la lengua española (RAE y ASALE)."}
};
const n=s=>typeof normalizeText==='function'?normalizeText(s):String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const crear=(t,x,c)=>{const e=document.createElement(t);if(x)e.textContent=x;if(c)e.className=c;return e};
const st=crear('style');st.textContent='.origen-boton{display:inline-flex;align-items:center;margin:0 0 .2em .45em;padding:.45em .75em;border:0;border-radius:6px;background:#1769c2;color:#fff;font:600 14px Arial,sans-serif;vertical-align:middle;cursor:pointer}.origen-boton:hover{background:#10539d}.origen-dialog{box-sizing:border-box;width:min(650px,calc(100% - 24px));padding:22px;border:1px solid #cbdce9;border-radius:14px;color:#263643;background:#fff;font:16px/1.5 Arial,sans-serif}.origen-dialog::backdrop{background:#142d446b}.origen-head{display:flex;justify-content:space-between;gap:12px}.origen-head h2{margin:0}.origen-cerrar{border:1px solid #cbdce9;border-radius:6px;background:#fff;padding:7px 12px}.origen-ruta{margin:24px 0;padding:16px 18px;border:1px solid #cbdce9;border-radius:12px;background:#f6fbff;font-size:18px;font-weight:600;line-height:1.8}.origen-paso{display:inline}.origen-flecha{padding:0 8px;color:#1769c2}.origen-nota{color:#536a7c}@media(max-width:650px){.origen-boton{font-size:12px}.origen-dialog{padding:15px}.origen-ruta{font-size:16px}}';document.head.appendChild(st);
let modal,ultimo;
function abrir(p,b){ultimo=b;modal&&modal.remove();modal=crear('dialog','','origen-dialog');const h=crear('div','','origen-head'),t=crear('h2','Origen de «'+p+'»'),c=crear('button','Cerrar','origen-cerrar');c.type='button';c.onclick=()=>modal.close();h.append(t,c);modal.append(h);const d=rutas[n(p)];if(d){const q=crear('div','','origen-ruta');d.ruta.forEach((x,i)=>{if(i)q.append(crear('span','→','origen-flecha'));q.append(crear('span',x,'origen-paso'))});modal.append(q,crear('p',d.texto,'origen-nota'))}else{modal.append(crear('p','La ruta etimológica de esta entrada todavía no está registrada.'))}modal.addEventListener('close',()=>ultimo&&ultimo.isConnected&&ultimo.focus());document.body.append(modal);modal.showModal();c.focus()}
function adjuntar(){const l=document.querySelector('#definition .term');if(!l||document.querySelector('#definition .origen-boton'))return;const marca=l.getAttribute('data-clave');const p=(marca&&Object.prototype.hasOwnProperty.call(dictionary,marca))?marca:Object.keys(dictionary).find(x=>n(x)===n(l.textContent.trim()));if(!p)return;const b=crear('button','Origen','origen-boton');b.type='button';b.setAttribute('aria-label','Ver origen de '+p);b.onclick=()=>abrir(p,b);const r=document.querySelector('#definition .relacionadas-boton');(r||l).insertAdjacentElement('afterend',b)}
new MutationObserver(adjuntar).observe(document.getElementById('definition'),{childList:true});adjuntar();
})();
